server:
  port: 8761

spring:
  application:
    name: spring_eureka_server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
